### ISSUE TITLE
Slow performance on parallel Tasks

### ISSUE THREAD

**Issue by karen7272** [blackducksoftware/hub-alert#54]
I have application which is divided into two parts.
It starts with single thread, than it creates 8 parallel Tasks.

Running this application on .Net framework 4.6 and .Net Core 2.0 (on the same machine) gives different performance results.

On parallel Tasks .Net Core 2.0 is about 15% slower than .Net Framework 4.6. But on single thread part .Net Core is faster about 5%.

Are there any ways to improve performance of parallel Tasks in .Net Core 2.0 ?

I use the following configuration for my application:

`<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
	<ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>`

**Comment by psantos1113** [comment]
This isn't an issue with this project.  This is not a .NET project. Closing this issue as it doesn't apply to this project at all.
